### ISSUE TITLE
how to use this tools

### ISSUE THREAD

**Issue by LeChenOS** [Alytona/MStar#1]
can you tell me how to use this tools. I want to unpack tcl.bin android8,thanks.

**Comment by Alytona** [comment]
Thank you for a question!
Please, see the new file how_to_use.doc.

**Comment by LeChenOS** [comment]
This tool supports Android 8or9？

**Comment by LeChenOS** [comment]
Please provide MstarGUI.exe download link。

**Comment by LeChenOS** [comment]
Please give me your contact information

**Comment by LeChenOS** [comment]
> Thank you for a question! Please, see the new file how_to_use.doc.

Please provide MstarGUI.exe download link。This tool supports Android 8or9？Please give me your contact information

**Comment by Alytona** [comment]
This tool was compiled only for Windows.
I have add the folder downloads, there is the archive with the executable for Windows.

**Comment by Alytona** [comment]
I can give you my mail address, but this will not make our communication faster.

**Comment by LeChenOS** [comment]
> 



> I can give you my mail address, but this will not make our communication faster.

Give me your compiled MstarGUI.exe,

**Comment by LeChenOS** [comment]
> I can give you my mail address, but this will not make our communication faster.

I use your mstarbintool GUI_ v2. 4.1. Au3 compiled. System and vendor cannot be saved

**Comment by LeChenOS** [comment]
> I can give you my mail address, but this will not make our communication faster.

Can you package your MstarGUI.exe compiled rar for me to download

**Comment by Alytona** [comment]
> Can you package your MstarGUI.exe compiled rar for me to download
https://github.com/Alytona/MStar/tree/master/downloads

**Comment by Alytona** [comment]
> I use your mstarbintool GUI_ v2. 4.1. Au3 compiled. System and vendor cannot be saved
I am not an author of  mstarbintool GUI_ v2. 4.1. Au3. I have got this source from the customer of the MStar.
I have used it for investigation of packing-unpacking technology.

**Comment by LeChenOS** [comment]
> I can give you my mail address, but this will not make our communication faster.

Do you have a telegram account

**Comment by LeChenOS** [comment]
> > I use your mstarbintool GUI_ v2. 4.1. Au3 compiled. System and vendor cannot be saved
> > I am not an author of  mstarbintool GUI_ v2. 4.1. Au3. I have got this source from the customer of the MStar.
> > I have used it for investigation of packing-unpacking technology.

Configuration file, please pack rar, have you tested Android 8 or 9

**Comment by Alytona** [comment]
I haven't tested this under Android 8 or 9. This project is for Windows only.
You don't need a configuration file, choose directory and work.

**Comment by Alytona** [comment]
Sorry, I forgot to add two libraries. Just a moment.

**Comment by Alytona** [comment]
Done

**Comment by LeChenOS** [comment]
> Sorry, I forgot to add two libraries. Just a moment.

https://github.com/sha-man-4pda/mstar-bin-tool
This tool supports Android 8. Can you add it？

**Comment by LeChenOS** [comment]
> Done

System. IO. FileNotFoundException: could not load the file or assembly 'spark_clr, version = 1.0.7718.30967, culture = neutral, publickeytoken = null' or one of its dependencies. The system cannot find the specified file.
File name: "spark_clr, version = 1.0.7718.30967, culture = neutral, publickeytoken = null"
In mstargui Partition. unpack(String workDirectory, FileStream firmwareStream, IMessageLogger messageLogger)
In mstargui MainWindow.<> c__ DisplayClass17_ 0.<UnpackButton_ Click>b__ 0()

**Comment by Alytona** [comment]
> System. IO. FileNotFoundException: could not load the file or assembly 'spark_clr
I don't know the file spark_clr. May be sparse_clr?
Did you run MStarGUI.cmd?

**Comment by Alytona** [comment]
Which file did you run?

**Comment by Alytona** [comment]
> https://github.com/sha-man-4pda/mstar-bin-tool This tool supports Android 8. Can you add it？
Sorry, I can't. This project is on Python. My project is on C++ and C#.

**Comment by LeChenOS** [comment]
> > System. IO. FileNotFoundException: could not load the file or assembly 'spark_clr
> > I don't know the file spark_clr. May be sparse_clr?
> > Did you run MStarGUI.cmd?

yes. I run mstargui.cmd

**Comment by LeChenOS** [comment]
> > System. IO. FileNotFoundException: could not load the file or assembly 'spark_clr
> > I don't know the file spark_clr. May be sparse_clr?
> > Did you run MStarGUI.cmd?

win10

**Comment by Alytona** [comment]
Can you attach screenshots of the error and directories?

**Comment by LeChenOS** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Alytona/MStar"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月29日(星期六) 晚上10:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Alytona/MStar] how to use this tools (Issue #1)





 
Can you attach screenshots of the error and directories?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LeChenOS** [comment]
> Can you attach screenshots of the error and directories?

- 

> > Can you package your MstarGUI.exe compiled rar for me to download
> > https://github.com/Alytona/MStar/tree/master/downloads



> Can you attach screenshots of the error and directories?

send your email

**Comment by Alytona** [comment]
aev2000@mail.ru
